apiVersion: v1
kind: Pod
metadata:
  name: demo-api
  labels:
    name: api
    owner: somkiat
    version: "1.0"
    environment: development
spec:
  containers:
    - name: demo-api
      image: somkiat/demo-api
      ports:
        - containerPort: 1323
          protocol: TCP